#!/bin/sh
# Write the fork's build info header (version, build date, commits) for the welcome screen.
#
#   tools/fork-build-info.sh OUT.h
#
# FORK_SINCE (environment) is the commit of the previous build (tools/windows/steam-fork.sh sets
# it to the one installed in the Steam folder); the header then lists the commits after it. Without
# it, or when nothing is new, it lists the latest commits. OUT.h is rewritten only when it changes.
# Prints nothing on stdout (the Makefile calls it through $(shell)).

out="${1:-fork_build_info.h}"
max=12
cd "$(dirname "$0")/.." || exit 0
git rev-parse --git-dir >/dev/null 2>&1 || exit 0

# 122.0-91-g6b68fcc(-dirty) -> 122.0+91 (6b68fcc, local changes)
desc="$(git describe --tags --dirty 2>/dev/null)"
count="$(git rev-list --count 122.0..HEAD 2>/dev/null || echo 0)"
hash="$(git rev-parse --short HEAD)"
version="122.0+$count ($hash)"
case "$desc" in *-dirty) version="122.0+$count ($hash, local changes)" ;; esac

since_version=""
range=""
if [ -n "${FORK_SINCE:-}" ] && git cat-file -e "$FORK_SINCE^{commit}" 2>/dev/null; then
	if [ -n "$(git rev-list --no-merges -n 1 "$FORK_SINCE..HEAD")" ]; then
		range="$FORK_SINCE..HEAD"
		since_version="122.0+$(git rev-list --count "122.0..$FORK_SINCE") ($(git rev-parse --short "$FORK_SINCE"))"
	fi
fi

# C string: escape backslashes, quotes and question marks (no trigraphs)
cstr() { sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g'; }

tmp="$out.tmp"
{
	echo "// generated by tools/fork-build-info.sh, not in git"
	echo "#define FORK_BUILD_VERSION \"$version\""
	echo "#define FORK_BUILD_DATE \"$(date '+%Y-%m-%d %H:%M')\""
	echo "#define FORK_BUILD_SINCE \"$since_version\""
	git log --no-merges --format=%s -n $max ${range:+"$range"} | cstr | {
		echo "static const char *const fork_build_commits[] = {"
		while IFS= read -r line; do
			echo "	\"$line\","
		done
		echo "	0"
		echo "};"
	}
	more=0
	if [ -n "$range" ]; then
		more=$(( $(git rev-list --no-merges --count "$range") - max ))
		[ $more -lt 0 ] && more=0
	fi
	echo "#define FORK_BUILD_MORE $more"
} > "$tmp"

if cmp -s "$tmp" "$out"; then
	rm -f "$tmp"
else
	mv -f "$tmp" "$out"
fi
